name: Auto Merge Codex PRs

on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
