name: Auto Merge Codex PRs

on:
  pull_request_target:
    # Run when codex-labeled pull requests are opened, updated,
    # marked ready for review, or labeled
    types: [opened, ready_for_review, synchronize, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    # The PRs are opened by SirLovi but automatically labeled "codex"
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
