name: CI
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install WebAssembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Cargo test
        run: cargo test --all
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g wasm-pack
      - name: Wasm tests
        run: wasm-pack test --node
